on:
  push:
    tags:
      - "v*"

name: Create Release

permissions: {}
jobs:
  build:
    permissions:
      contents: write

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release for tag
        id: release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Please refer to [CHANGELOG.md](https://github.com/dataiku/solutions-contrib/blob/${{ github.ref }}/CHANGELOG.md) for details.
